apps:
- name: teste-meu-guru-back-end
  cwd: ./backend
  script: npm
  args: "run start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  watch: true
  env:
    PORT: 3001
- name: teste-meu-guru-front-end
  cwd: ./frontend
  script: npm
  args: "start"
  exec_mode: fork
  max_restarts: 3
  max_memory_restart: 200M
  env:
    PORT: 3000